<div class="container">
    <div class="row">
        <div class="col-6 bg-info mt-5 mx-auto">
            <h4 class="text-center text-light mt-3">Введите новый пароль</h4>
            <?= $this->tag->form('reset');?>
            <?php echo $form->render('password',["class" => "form-control my-5 w-100","placeholder" =>"пароль"]); ?>
            <?php echo $form->render('confirmPassword',["class" => "form-control my-5 w-100","placeholder" =>"пароль"]); ?>
            <?= $this->tag->submitButton(['Подтвердить', 'class'=>'btn btn-light mx-auto w-25']);?>
            <span><?= $this->tag->linkTo(['time-tracker/team','Назад',"class" => "btn btn-danger w-25"]); ?></span>
            <?= $this->tag->endForm();?>
        </div>
    </div>
</div>