<?php $this->assets->addCss('//maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css',false); ?>
<div class="container my-5">
    <div class="alert alert-success">
        <?= $this->getContent(); ?>
    </div>
  <div class="col-4 mx-auto">
    <ul class="navbar-nav">
        <li class="nav-item">
            <?= $this->tag->linkTo(["admin/create", "Создать пользователя","class"=>"btn btn-info w-100"]) ?>
        </li>
        <li class="nav-item">
            <?= $this->tag->linkTo(['admin/users ', 'Посмотреть всех пользователей', 'class' => 'btn btn-info my-2 w-100']) ?>
        </li>
        <li class="nav-item">
            <?= $this->tag->linkTo(["delete_user", "Изминение юзера","class" => "btn btn-info mb-2 w-100"]) ?>
        </li>
        <li class="nav-item">
            <?= $this->tag->linkTo(["admin/getHolidays", "Посмотреть не рабочие дни","class" => "btn btn-info mb-2 w-100"]) ?>
        </li>
        <li class="nav-item">
            <?= $this->tag->linkTo(["admin/manipulateHolidays", "Create holidays","class" => "btn btn-info mb-2 w-100"]) ?>
        </li>
        <li class="nav-item">
            <?= $this->tag->linkTo(["admin/logout", "Выйти","class" => "btn btn-danger w-100    "]) ?>
        </li>
    </ul>
  </div>
</div>