 <div class="float-right mt-2 mr-2">
        <?= $this->tag->linkTo(["admin/users", "Назад","class" => "btn btn-danger px-5"]) ?>
 </div>
 <div class="clearfix"></div>
<div class="container my-2">
    <div class="row">
        <div class="col-6 mx-auto">
            <?= $this->tag->form('admin/searchDataByDate'); ?>
            <?php echo $form->render('year',['class' => 'form-control w-25 my-2 d-inline w-100','name'=>'year']); ?>
            <?php echo $form->render('month',['class' => 'form-control w-25 my-2 d-inline w-100','name'=>'month']); ?>
            <?php echo $form->render('hiddenUserId',['name'=>'hidden',"value" =>$user['id']]);?>
            <button type="submit" class="btn btn-info mb-2 w-100" id="btnSearch">Искать</button>
            </form>
        </div>
        <div class="col-8 mx-auto">
            <div class="alert alert-success" role="alert">
                <?php
                echo "<strong>"."Имя пользователя: "."</strong>" .$user['first_name']."<br>";
                echo (isset($assignedHours))? "<strong>Assigned: </strong> ".$assignedHours."<br>" : "<strong>Assigned: </strong><br>";
                echo (isset($totalLateHours)) ? "<strong>Late hours:</strong>".$totalLateHours."<br>" : "<strong>Late hours:</strong><br>";
                echo "<strong>You have/Assigned: </strong>".$hourInPercent."%"."<br>";
                 echo $this->getContent(); ?>
            </div>
            </div>
        </div>
        <div class="col-12">
            <table class="table table-dark" border="1">
                <tbody>
                <tr>
                    <th>Data</th>
                    <?php if(isset($user)) { $k = 0; for ($i =0; $i < 1; $i++) { ?>
                        <th>
                            <h5 class="text-success">
                                <?= $user['first_name'];  ?>
                            </h5>
                        </th>
                    <?php } }?>
                </tr>
                <?php if (isset($daysInMonth)) { for ($i = 1, $j = 1; $i <= $daysInMonth; $i++, $j++) { ?>

                    <tr>
                        <td>
                            <?php
                            foreach ($holidays as $holiday)
                            {
                                if (date('Y-m-d', strtotime($date->format("$year-$month-$j"))) == $holiday->holiday_date)
                                {
                                    echo "<span class='text-danger'>Не рабочий день из-за $holiday->holiday</span><br>";
                                }
                            }
                                $nameOFDay = date('l', strtotime($date->format("$year-$month-$j")));
                                echo ($nameOFDay == 'Saturday' || $nameOFDay == 'Sunday') ?
                                    "<span class='text-warning'>" . $date->format("$j") . "<br>" . $nameOFDay . "</span>"
                                    : $date->format("$j") . "<br>" . $nameOFDay;
                              ?>
                        </td>

                        <?php if(isset($user['times'])) { foreach ($user['times'] as $arr) { ?>
                                <?php
                                if (isset($arr))
                                {
                                        if
                                        (    $arr['date_tracker'] == $date->format("$year").'-0'.$date->format("$month").'-0'.$date->format("$j") ||
                                            $arr['date_tracker'] == $date->format("$year").'-'.$date->format("$month").'-'.$date->format("$j") ||
                                            $arr['date_tracker'] == $date->format("$year").'-0'.$date->format("$month").'-'.$date->format("$j")||
                                            $arr['date_tracker'] == $date->format("$year").'-'.$date->format("$month").'-0'.$date->format("$j")
                                        )
                                     {       ?>
                                            <td>
                                                <?= $this->tag->form('admin/updateTime');?>
                                                <small class="form-text text-muted pl-4">Started</small>
                                                <?php echo $timeForm->render('time',['name'=>'start_time',"class" => "form-control w-50","value" =>$arr['start_time']]);?>
                                                <small class="form-text text-muted pl-4">Finished</small>
                                                <?php echo $timeForm->render('time',['name'=>'stop_time',"class" => "form-control w-50","value" =>$arr['stop_time']]);?>
                                                <small class="form-text text-muted pl-4">Total</small>
                                                <?php echo $timeForm->render('time',['name'=>'total',"class" => "form-control w-50","value" =>$arr['total']]);?>
                                                <small class="form-text text-muted pl-4">He was late</small>
                                                <?php echo $timeForm->render('time',['name'=>'late',"class" => "form-control w-50","value" =>$arr['late']]);?>
                                                <small class="form-text text-muted pl-4">Assigned</small>
                                                <?php echo $timeForm->render('time',['name'=>'assigned',"class" => "form-control w-50","value" =>$arr['assigned']]);?>
                                                <?php echo $timeForm->render('time_id',['name'=>'hiden',"value" =>$arr['time_id']]);?>
                                                <?= $this->tag->submitButton(['Сохранить изменение', 'class'=>'btn btn-primary mt-3 w-50']);?>
                                                <?= $this->tag->endForm();?>
                                            </td>
                                   <?php } } ?>

                        <?php }} ?>
                    </tr>
                <?php } }?>
                </tbody>
            </table>
        </div>
    </div>
</div>

