<html>
<head>
    <title>Главная</title>
    <?php $this->assets->addCss('//maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css',false); ?>
    <?php $this->assets->addCss('css/style.css'); ?>
    <?php $this->assets->outputCss(); ?>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-info justify-content-between">
        <a class="navbar-brand" href="#">Growave</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto text-light">
                <li class="nav-item">
                    <?= $this->tag->linkTo(["/", "Главная","class"=>"nav-link text-light"]) ?>
                </li>
                <li class="nav-item">
                    <?= $this->tag->linkTo(["index/about", "About","class"=>"nav-link text-light"]) ?>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <col-12>
            <h5>Главная страница</h5>
        </col-12>
    </div>
</div>
</body>
<html>
<?php echo $this->getContent();
echo $this->assets->outputJs();
?>