<!--<div class="container">
    <div class="row">
        <div class="col-8 mx-auto">
            <h1 class="text-center mt-5">STAFF</h1>
                <?php
/*                foreach ($users as $user) { */?>
            <table border="1">
                <caption>Users table</caption>
                <tr>
                    <th>id</th>
                    <th>Name</th>
                    <th>Second Name</th>
                    <th>Email</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td><?/*= $user->id; */?></td>
                    <td><?/*= $user->first_name; */?></td>
                    <td><?/*= $user->second_name; */?></td>
                    <td><?/*= $user->email; */?></td>
                    <td><?/*= $user->privilege; */?></td>
                </tr>
            </table>
            <?php /*} */?>
        </div>
    </div>
</div>-->