<header>
 <nav class="navbar navbar-expand-lg navbar-light bg-info justify-content-between">
        <a class="navbar-brand" href="#">Growave</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto text-light">
                <li class="nav-item">
                    <?= $this->tag->linkTo(["/", "Главная","class"=>"nav-link text-light"]) ?>
                </li>
                <li class="nav-item">
                    <?= $this->tag->linkTo(["sign/index", "Sign in","class"=>"nav-link text-light"]) ?>
                </li>
                <li class="nav-item">
                    <?= $this->tag->linkTo(["sign/signOut", "Sign out","class"=>"nav-link text-light"]) ?>
                </li>
            </ul>
        </div>
    </nav>
</header>
<?php echo $this->getContent();
echo $this->assets->outputJs();
?>